/// Flutter icons HobbiesIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  HobbiesIcons
///      fonts:
///       - asset: fonts/HobbiesIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class HobbiesIcons {
  HobbiesIcons._();

  static const _kFontFam = 'HobbiesIcons';

  static const IconData yoga = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData gym = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData running = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData cycling = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData swimming = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData dancing = const IconData(0xe805, fontFamily: _kFontFam);
}
